config/routes.rb
Fugue::Application.routes.draw do
  resources :pieces, :only => [:index, :show, :edit, :update, :destroy]
  root :to => 'pieces#index'
end

app/models/note.rb
class Note
  include Mongoid::Document

  field :pitch, :type => Integer
  field :start, :type => Integer
  field :length, :type => Integer
  embedded_in :track, :inverse_of => :notes
end

app/models/piece.rb
class Piece
  include Mongoid::Document

  field :title
  field :tempo, :type => Integer
  field :division, :type => Integer
  embeds_many :tracks
  
  accepts_nested_attributes_for :tracks
end

app/models/track.rb
class Track
  include Mongoid::Document

  field :title
  embedded_in :piece, :inverse_of => :tracks
  embeds_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  def index
    @pieces = Piece.all
  end

  def show
    @piece = Piece.find(params[:id])
  end

  def edit
    @piece = Piece.find(params[:id])
  end

  def update
    @piece = Piece.find(params[:id])
    if @piece.update_attributes(params[:piece])
      flash[:notice] = "Update successful."
      redirect_to @piece
    else
      flash[:notice] = "Update failed."
      render :action => :edit
    end
  end
  
  def destroy
    @piece = Piece.find(params[:id])
    @piece.destroy
    redirect_to pieces_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
  def note_height_ratio
    @note_height_ratio ||= 100.0 / @piece.division
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
  = stylesheet_link_tag 'compiled/print.css', :media => 'print'
  /[if IE]
    = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection' 
  = csrf_meta_tag
  /[if lt IE 9]
    = javascript_include_tag 'html5'
%body
  = yield
  = javascript_include_tag :defaults

app/views/pieces/edit.html.haml
%h1 Editing a piece
= form_for @piece do |f|
  %p
    = f.label :title
    = f.text_field :title
  %p
    = f.label :tempo
    = f.text_field :tempo
  %p Track titles:
  %ul
    = f.fields_for :tracks do |track_f|
      %li
        = track_f.text_field :title
  %p
    = f.submit 'Update'

app/views/pieces/index.html.haml
%h1 The Art of Fugue
%ul
  - @pieces.each do |piece|
    %li
      = link_to piece.title, piece
      = link_to "Destroy", piece, :confirm => "Are you sure?", :method => :delete

app/views/pieces/show.html.haml
%h1= @piece.title
%p
  = link_to 'Edit', edit_piece_path(@piece)
%div#piece
  - @piece.tracks.each_with_index do |track, track_index|
    - track.notes.each do |note|
      %div.note{:class => "pitch-#{note.pitch} track#{track_index}", :style => "top: #{note.start * note_height_ratio}px; min-height: #{note.length * note_height_ratio}px;"}
        &nbsp; 